### ISSUE TITLE
Add other auth providers

### ISSUE THREAD

**Issue by MathisBurger** [MathisBurger/CodeCanvas#32]
- Login with Github
- Login with Google
- Login with Reddit?

**Comment by oleggtro** [comment]
Login with microsoft to support university signup

**Comment by oleggtro** [comment]
We most likely will have to update our privacy policy as we're now exchanging data with Microsoft.
Additionally we [have to link to our privacy statement](https://learn.microsoft.com/en-us/entra/identity-platform/howto-add-terms-of-service-privacy-statement) in the apps documentation on MSs end.

They even have a tutorial on how to handle authentication with react [here](https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-single-page-app-react-sign-in). I've not taken a look in detail, but it seems pretty usable
