### ISSUE TITLE
Spotlight Stage2

### ISSUE THREAD

**Issue by MathisBurger** [MathisBurger/CodeCanvas#60]

**Comment by oleggtro** [comment]
Maybe using [meilisearch](https://github.com/meilisearch) would be worth a shot if we want to search through single answers, assignments and stufe. Although it would mean introducting another dependency...

**Comment by MathisBurger** [comment]
This indeed would be a nice solution. But I would consider it more as an option for Stage3 Spotlight, because Stage2 only includes browser internal search results. 
I will add a new issue for Spotlight Stage3 and add meilisearch as an option for solving the problem
